### ISSUE TITLE
Nome do grupo

### ISSUE THREAD

**Issue by BeCouto** [Projetos-de-Extensao/PFE_24.2_8001_II_RaveBreaking#1]
Ajudem a escolher um nome para nosso grupo
- deve ser baseado em eventos/temas de surf
- possivel referencia a serie breaking bad
- aberto a sugestoes 

POSSIVEIS NOMES:
-WaveEventHub
-Better Catch Waves
-Surfing Bad
-Wave Breaking
-Breaking Surf

**Comment by vikxzzzz** [comment]
Eu gostei do Wave Breaking

**Comment by Ferrett27** [comment]
Eu gostei do Better Catch Waves

**Comment by sarahferrarir** [comment]
Eu tbm gostei do Wave Breaking

**Comment by sarahferrarir** [comment]
Precisamos de um novo nome para nosso grupo né

**Comment by Pedro0Silvestre** [comment]
Verdade. Pq n coloca só grupo lolla?

**Comment by sarahferrarir** [comment]
por mim pode ser
