### ISSUE TITLE
Pesquisa de campo

### ISSUE THREAD

**Issue by BeCouto** [Projetos-de-Extensao/PFE_24.2_8001_II_RaveBreaking#2]
- [x]  Procurar por sites sobre eventos/ temas de surf
- [x] Mandar link nos comentarios de sites que gostaram 
- [x] sugerir um local para o nosso evento
- [x] Apresentar serviços que irão ter no evento
- [x] Apresentar as principais atraçoes dentro do evento ( menos a competiçao obviamente )

**Comment by Pedro0Silvestre** [comment]
iram? o evento é no irã?

**Comment by vikxzzzz** [comment]
Procurar por sites sobre eventos / temas de surf:

1. https://cbsurf.org.br/
2. https://www.worldsurfleague.com/
3. https://wsllatinamerica.com/
4. https://wavessurfcampperu.com/

**Comment by Pedro0Silvestre** [comment]
lollapalooza 2025
- local: Autódromo de Interlagos, em São Paulo
- hospedagens: https://www.letsatlantica.com.br/hotel-perto-do-lollapalooza
- restaurantes:
  - no envento: https://www.estadao.com.br/paladar/radar/saiba-onde-comer-no-lollapalooza-2024/
  - fora:https://www.tripadvisor.com.br/RestaurantsNear-g303631-d12375582-Interlagos_Autodromo_Suites_Individuais_Em_Casa-Sao_Paulo_State_of_Sao_Paulo.html
- hospitais:
  - Hospital Maternidade Interlagos - "Waldemar Seyssel Arrelia"
  -AME Interlagos M.C.C
  - Ambulatório Maternidade Interlagos
  - Hospital Geral de Pedreira
  - Atrações: https://www.queroviajarmais.com/lollapalooza/
    - https://www.tripadvisor.com.br/AttractionsNear-g303631-d2349931-Autodromo_Jose_Carlos_Pace-Sao_Paulo_State_of_Sao_Paulo.html

**Comment by Pedro0Silvestre** [comment]
atrações do evento: https://www.lollapaloozabr.com/
