### ISSUE TITLE
Criar o Brainstorm

### ISSUE THREAD

**Issue by Ferrett27** [Projetos-de-Extensao/PFE_24.2_8001_II_RaveBreaking#5]
O arquivo brainstorm está disponível na pasta /docs/base.
- [x] Responder as perguntas do brainstorm. 
- [x] Criar requisitos funcionais e não funcionais (requisitos elicitados). 
- [x] Alterar a parte de "Metodologia".

**Comment by sarahferrarir** [comment]
Respondi algumas perguntas do brainstorm, mas fiquei em dúvida sobre o que seria o "produto".

**Comment by sarahferrarir** [comment]
botei já requisitos funcionais e não funcionais, mas ele vai explicar isso na próxima aula só

**Comment by sarahferrarir** [comment]
brainstorm atualizado.
